### ISSUE TITLE
Prevent user to assign hours without a task

### ISSUE THREAD

**Issue by velteyn** [maxrossello/redmine_app_timesheets#49]
Hello,
we have a problem here. We see that users can assign development time without a specific task.

This is good for vacations etc but its not desirable  for development activities...

How can we prevent this ?

**Comment by maxrossello** [comment]
Hi,
even with standard Redmine you cannot prevent a user to assign time to the project rather than over issues. There is no way to force time assignment on issues, you have to enforce it through your process. 
However, my suggestion is to use standard Redmine facilities to track time for development  (they are there on purpose), and use the timesheet app for administrative purposes only.
