### ISSUE TITLE
Orders/Issues are transcribed to next period

### ISSUE THREAD

**Issue by fafnir1990** [maxrossello/redmine_app_timesheets#82]
Hello,
Your application is very useful, but I found one inconvenience. Is it possible to block transcription of issues to the next period of time?
I`m asking, because issues rows are accumulating and after some periods, size of TS is enormous.
Is it possible to solve my problem? I may try to change the code but  if you don`t have a time for that, but I don`t know which file and line is responsible for copying rows.

As I sad You have don a very good and useful job.

Best wishes
Rafał

**Comment by maxrossello** [comment]
Hi,
of course it is possible since it was hard to implement that :-)

Have a look at https://github.com/maxrossello/redmine_app_timesheets/blob/master/app/controllers/timesheets_controller.rb at line 329. The number of timesheet day entries is defined between @period_start-@period_length and @period_end+@period_length. With this setup, the overall length of a row is 3x@period_length.
Just use plain simple @period_start and @period_end here and you should have no row transcriptions to the previous and following time periods.

Regards,
  Massimo

**Comment by fafnir1990** [comment]
Great, thank you, it works!

**Comment by maxrossello** [comment]
Great to know. Thank you!
