### ISSUE TITLE
Spent time reports

### ISSUE THREAD

**Issue by fafnir1990** [maxrossello/redmine_app_timesheets#83]
Hello
As you have written in readme
"Spent time reports (/time_entries/report) use Orders as a new split criteria"
It`s a great functionality, but I need a hint...

Situation:
I have 5 projects, each include subprojects with one version.
I would like to display Spent time report with filter by project, but ofter filtration subprojects`s versions are not visible in report.
How can I display spent time on versions from one Project?

Thanks for any help
Best regards :)

**Comment by maxrossello** [comment]
"definition and visibility permissions on local Orders are under control of the project's managers"

so in order to see a local Order as a split criteria for a super project:
1. the Version must be declared as an Order
2. it must be shared up the tree

if the Version is not shared, thus with visibility confined in the sub-project, so will also the related local Order

**Comment by fafnir1990** [comment]
Ok, thank you very much!
